FROM codercom/code-server

# RUN apt update && apt upgrade -y

# RUN apt install -y  python3 \
#                     python3-pip

# ## START - Python packages
# ADD requirements.txt .
# RUN pip3 install -r requirements.txt
# ## END - Python packages

# WORKDIR /home
