version: '3.8'

services: 
    vscode-server:
        image: "knoriy/vscode-server"
        build: "./"
        container_name: vscode-server
        # volumes:
        # - /home/$USER:/home/
        # restart: always
        # ports:
        # - "5000:5000"
        # environment:
        # - type=lab
        