FROM tensorflow/tensorflow:1.9.0-devel-gpu-py3

RUN apt update

# ## START - Python packages
# ADD requirements.txt .
# RUN pip3 install -r requirements.txt
# ## END - Python packages

WORKDIR /home

CMD [ "bash" ]